# ./docker-compose.yml
version: '3'

services:
  app:
    image: adhocore/lemp:8.0
    # For different app you can use different names. (eg: )
    container_name: ci3_502014_com
    volumes:
      # app source code
      - C:\Users\jim\Documents\jim_test:/var/www/html
      # db data persistence
      - db_data:/var/lib/mysql
      # Here you can also volume php ini settings
      # - /path/to/zz-overrides:/usr/local/etc/php/conf.d/zz-overrides.ini
    ports:
      - 80:80
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root***
      MYSQL_DATABASE: testSQL
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuser
      # for postgres you can pass in similar env as for mysql but with PGSQL_ prefix

volumes:
  db_data: {}